from typing import Literal
import io
import time

import discord
from discord import app_commands
import fal_client
import httpx

from fal_bot import config

# Configure fal_client
fal_client.api_key = config.FAL_SECRET

@app_commands.command(
    name="hunyuan",
    description="Generate an image using Hunyuan Image 3.0 text-to-image model",
)
@app_commands.choices(aspect_ratio=[
    app_commands.Choice(name="Square HD", value="square_hd"),
    app_commands.Choice(name="Square", value="square"),
    app_commands.Choice(name="Portrait 4:3", value="portrait_4_3"),
    app_commands.Choice(name="Portrait 16:9", value="portrait_16_9"),
    app_commands.Choice(name="Landscape 4:3", value="landscape_4_3"),
    app_commands.Choice(name="Landscape 16:9", value="landscape_16_9"),
])
async def command(
    interaction: discord.Interaction,
    prompt: str,
    aspect_ratio: str,
):
    """Generate images using Hunyuan Image 3.0"""
    
    await interaction.response.send_message("🎨 Your image generation request has been received...")
    
    # Prepare arguments
    arguments = {
        "prompt": prompt,
        "image_size": aspect_ratio,
    }
    
    start_time = time.time()
    
    try:
        # Define callback for queue updates
        def on_queue_update(update):
            if isinstance(update, fal_client.InProgress):
                for log in update.logs:
                    print(f"[Hunyuan] {log.get('message', '')}")
        
        # Submit request and wait for result
        result = await fal_client.subscribe_async(
            "fal-ai/hunyuan-image/v3/text-to-image",
            arguments=arguments,
            with_logs=True,
            on_queue_update=on_queue_update,
        )
        
    except Exception as e:
        await interaction.edit_original_response(
            content=f"❌ Error generating image: {str(e)}"
        )
        return

    if result is None or "images" not in result:
        await interaction.edit_original_response(
            content="❌ Failed to generate image. Please try again."
        )
        return

    elapsed_time = time.time() - start_time
    
    # Process generated images
    images = result["images"]
    
    aspect_ratio_map = {
    "square_hd": "Square HD",
    "square": "Square",
    "portrait_4_3": "Portrait 4:3",
    "portrait_16_9": "Portrait 16:9",
    "landscape_4_3": "Landscape 4:3",
    "landscape_16_9": "Landscape 16:9",
}
    aspect_ratio_display = aspect_ratio_map.get(aspect_ratio, aspect_ratio)
    
    
    # Create embed with metadata
    embed = discord.Embed(
        title="🎨 Hunyuan Image 3.0",
        description=f"**Prompt:** {prompt}",
        color=discord.Color.purple()
    )
    
    embed.add_field(name="Aspect Ratio", value=aspect_ratio_display, inline=True)
    embed.add_field(name="Time Taken", value=f"{elapsed_time:.1f}s", inline=True)
    embed.add_field(name="Generated by", value=interaction.user.mention, inline=True)

    
    # Set the first image in the embed (no file attachment)
    if images:
        embed.set_image(url=images[0]["url"])
    
    # Send only the embed (no file attachments)
    await interaction.edit_original_response(
        content=None,
        embed=embed,
    )