from typing import Literal
import io

import discord
from discord import app_commands
import fal_client
import httpx

from fal_bot import config, utils, moderation  # Added moderation here
from fal_bot.consts import OVI_RESOLUTIONS

# Configure fal_client with your API key
fal_client.api_key = config.FAL_SECRET

@app_commands.command(
    name="ovi",
    description="Generate a video using Ovi text-to-video or image-to-video model",
)
async def command(
    interaction: discord.Interaction,
    mode: Literal["text-to-video", "image-to-video"],
    prompt: str,
    image: discord.Attachment | None = None,
):
    # Validate image requirement for image-to-video mode
    if mode == "image-to-video" and image is None:
        await interaction.response.send_message(
            "❌ Image is required for image-to-video mode. Please upload an image.",
            ephemeral=True
        )
        return
    
    # Validate image type if provided
    if image and not image.content_type.startswith('image/'):
        await interaction.response.send_message(
            "❌ Please upload a valid image file.",
            ephemeral=True
        )
        return

    # FIRST response - only do this ONCE
    await interaction.response.send_message("🔍 Checking content safety...")

    # Moderate the request
    image_url = image.url if image else None
    is_safe, reason = await moderation.moderate_request(prompt, image_url)

    if not is_safe:
        await interaction.edit_original_response(
            content=f"🚫 **Content Blocked**\n\n{reason}"
        )
        return

    await interaction.edit_original_response(
        content="🎬 Your video generation request has been received..."
    )
    
    # Determine the model endpoint and arguments based on mode
    if mode == "text-to-video":
        model_endpoint = "fal-ai/ovi"
        arguments = {
            "prompt": prompt,
        }
    else:  # image-to-video
        model_endpoint = "fal-ai/ovi/image-to-video"
        arguments = {
            "prompt": prompt,
            "image_url": image.url,
        }
    
    # Track time
    import time
    start_time = time.time()
    
    try:
        # Define callback for queue updates
        def on_queue_update(update):
            if isinstance(update, fal_client.InProgress):
                for log in update.logs:
                    print(f"[Ovi] {log.get('message', '')}")
        
        # Submit request and wait for result
        result = await fal_client.subscribe_async(
            model_endpoint,
            arguments=arguments,
            with_logs=True,
            on_queue_update=on_queue_update,
        )
        
    except Exception as e:
        await interaction.edit_original_response(
            content=f"❌ Error generating video: {str(e)}"
        )
        return

    if result is None:
        await interaction.edit_original_response(
            content="❌ Failed to generate video. Please try again."
        )
        return

    elapsed_time = time.time() - start_time
    
    # Download the video
    video_url = result["video"]["url"]
    
    try:
        await interaction.edit_original_response(
            content="⬇️ Downloading video..."
        )
        
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.get(video_url)
            response.raise_for_status()
            video_data = response.content
        
        # Check file size (Discord limit is 25MB for free servers)
        file_size_mb = len(video_data) / (1024 * 1024)
        
        if file_size_mb > 25:
            # File too large, send link instead
            embed = discord.Embed(
                title="🎬 Ovi Generated Video",
                description=f"**Prompt:** {prompt}\n\n⚠️ Video is too large ({file_size_mb:.1f}MB) to upload directly.\n\n[**Click here to download**]({video_url})",
                color=discord.Color.blue()
            )
            embed.add_field(name="Mode", value=mode, inline=True)
            embed.add_field(name="Time Taken", value=f"{elapsed_time:.1f}s", inline=True)
            embed.add_field(name="Generated by", value=interaction.user.mention, inline=True)
            
            await interaction.edit_original_response(
                content=None,
                embed=embed,
            )
        else:
            # Create Discord file from video data
            video_file = discord.File(
                io.BytesIO(video_data),
                filename="ovi_video.mp4"
            )
            
            # Create embed with metadata
            embed = discord.Embed(
                title="🎬 Ovi Generated Video",
                description=f"**Prompt:** {prompt}",
                color=discord.Color.blue()
            )
            embed.add_field(name="Mode", value=mode, inline=True)
            embed.add_field(name="File Size", value=f"{file_size_mb:.1f}MB", inline=True)
            embed.add_field(name="Time Taken", value=f"{elapsed_time:.1f}s", inline=True)
            embed.add_field(name="Generated by", value=interaction.user.mention, inline=True)
            
            # Send video file with embed
            await interaction.edit_original_response(
                content=None,
                attachments=[video_file],
                embed=embed,
            )
        
    except Exception as e:
        # If download fails, fall back to showing the link
        embed = discord.Embed(
            title="🎬 Ovi Generated Video",
            description=f"**Prompt:** {prompt}\n\n[**Click here to view**]({video_url})",
            color=discord.Color.orange()
        )
        embed.add_field(name="Mode", value=mode, inline=True)
        embed.add_field(name="Time Taken", value=f"{elapsed_time:.1f}s", inline=True)
        embed.add_field(name="Generated by", value=interaction.user.mention, inline=True)
        
        await interaction.edit_original_response(
            content=f"⚠️ Could not download video: {str(e)}",
            embed=embed,
        )