from typing import Literal
import io

import discord
from discord import app_commands
import fal_client
import httpx

from fal_bot import config, utils
from fal_bot.consts import OVI_RESOLUTIONS

# Configure fal_client with your API key
fal_client.api_key = config.FAL_SECRET

@app_commands.command(
    name="ovi",
    description="Generate a video using Ovi text-to-video or image-to-video model",
)
@app_commands.autocomplete(resolution=utils.autocomplete_from(OVI_RESOLUTIONS))
async def command(
    interaction: discord.Interaction,
    prompt: str,
    mode: Literal["text-to-video", "image-to-video"] = "text-to-video",
    negative_prompt: str = "jitter, bad hands, blur, distortion",
    num_inference_steps: int = 30,
    audio_negative_prompt: str = "robotic, muffled, echo, distorted",
    resolution: str = "992x512",
    seed: int | None = None,
    image: discord.Attachment | None = None,
):
    # Validate image requirement for image-to-video mode
    if mode == "image-to-video" and image is None:
        await interaction.response.send_message(
            "❌ Image is required for image-to-video mode. Please upload an image.",
            ephemeral=True
        )
        return
    
    # Validate image type if provided
    if image and not image.content_type.startswith('image/'):
        await interaction.response.send_message(
            "❌ Please upload a valid image file.",
            ephemeral=True
        )
        return

    await interaction.response.send_message("Your video generation request has been received.")
    
    # Determine the model endpoint and arguments based on mode
    if mode == "text-to-video":
        model_endpoint = "fal-ai/ovi"
        arguments = {
            "prompt": prompt,
            "negative_prompt": negative_prompt,
            "num_inference_steps": num_inference_steps,
            "audio_negative_prompt": audio_negative_prompt,
            "resolution": resolution,
        }
    else:  # image-to-video
        model_endpoint = "fal-ai/ovi/image-to-video"
        arguments = {
            "prompt": prompt,
            "negative_prompt": negative_prompt,
            "num_inference_steps": num_inference_steps,
            "audio_negative_prompt": audio_negative_prompt,
            "image_url": image.url,
        }
    
    if seed is not None:
        arguments["seed"] = seed
    
    # Track time
    with utils.Timed() as timer:
        try:
            # Define callback for queue updates
            def on_queue_update(update):
                if isinstance(update, fal_client.InProgress):
                    for log in update.logs:
                        print(f"[Ovi] {log.get('message', '')}")
            
            # Submit request and wait for result
            result = await fal_client.subscribe_async(
                model_endpoint,
                arguments=arguments,
                with_logs=True,
                on_queue_update=on_queue_update,
            )
            
        except Exception as e:
            await interaction.edit_original_response(
                content=f"❌ Error generating video: {str(e)}"
            )
            return

    if result is None:
        await interaction.edit_original_response(
            content="❌ Failed to generate video. Please try again."
        )
        return

    # Download the video
    video_url = result["video"]["url"]
    
    try:
        await interaction.edit_original_response(
            content="⬇️ Downloading video..."
        )
        
        async with httpx.AsyncClient() as client:
            response = await client.get(video_url)
            response.raise_for_status()
            video_data = response.content
        
        # Create Discord file from video data
        video_file = discord.File(
            io.BytesIO(video_data),
            filename="ovi_generated_video.mp4"
        )
        
        # Create embed with metadata
        embed = discord.Embed(
            title="Ovi Generated Video",
            description=f"**Prompt:** {prompt}",
            color=discord.Color.blue()
        )
        embed.add_field(name="Mode", value=mode, inline=True)
        embed.add_field(name="Resolution", value=resolution if mode == "text-to-video" else "N/A", inline=True)
        embed.add_field(name="Inference Steps", value=num_inference_steps, inline=True)
        embed.add_field(name="Seed", value=result.get("seed", "Random"), inline=True)
        embed.add_field(name="Time Taken", value=f"{timer.elapsed:.2f}s", inline=True)
        embed.add_field(name="Generated by", value=interaction.user.mention, inline=True)
        embed.set_footer(
            text="Powered by serverless.fal.ai",
            icon_url=config.FALAI_LOGO_URL,
        )
        
        # Send video file with embed
        await interaction.edit_original_response(
            content=None,
            attachments=[video_file],
            embed=embed,
        )
        
    except Exception as e:
        # If download fails, fall back to showing the link
        embed = discord.Embed(
            title="Ovi Generated Video",
            description=f"For the full resolution video, click [here]({video_url}).",
            color=discord.Color.blue()
        )
        embed.add_field(name="Prompt", value=prompt, inline=False)
        embed.add_field(name="Mode", value=mode, inline=True)
        embed.add_field(name="Resolution", value=resolution if mode == "text-to-video" else "N/A", inline=True)
        embed.add_field(name="Inference Steps", value=num_inference_steps, inline=True)
        embed.add_field(name="Seed", value=result.get("seed", "Random"), inline=True)
        embed.add_field(name="Time Taken", value=f"{timer.elapsed:.2f}s", inline=True)
        embed.add_field(name="Generated by", value=interaction.user.mention, inline=True)
        embed.set_footer(
            text="Powered by serverless.fal.ai",
            icon_url=config.FALAI_LOGO_URL,
        )
        
        await interaction.edit_original_response(
            content=f"⚠️ Video too large to upload directly. Download it here: {video_url}",
            embed=embed,
        )
        